version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    entrypoint: /usr/local/bin/custom-entrypoint.sh
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=5
      -c max_wal_senders=5
      -c hot_standby=off

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-gui
    restart: always
    ports:
      - "5540:5540"

volumes:
  pgdata:
